In [53]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

In [2]:
model_repo = 'gpt2'

In [18]:
tokenizer = AutoTokenizer.from_pretrained(model_repo)
model = AutoModelForCausalLM.from_pretrained(model_repo)
tokenizer.pad_token_id = tokenizer.eos_token_id

In [35]:
prompt = 'How to walk a cat'

In [36]:
inputs = tokenizer(prompt, return_tensors='pt')
inputs

{'input_ids': tensor([[2437,  284, 2513,  257, 3797]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}

In [22]:
outputs = model.generate(**inputs)
print(outputs)
tokenizer.batch_decode(outputs)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[2437,  284,  787,  257, 8263,  286,  257, 2095,  198,  198,  464,  717,
         1517,  345,  761,  284,  466,  318,  284, 3197]])


['How to make a drawing of a character\n\nThe first thing you need to do is to draw']

In [37]:
# temporary
input_embeds = model.get_input_embeddings()(inputs.input_ids)
input_embeds.size()

torch.Size([1, 5, 768])

In [38]:
output_embed = model.generate(inputs_embeds=input_embeds)
output_embed

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[50256,   198,   198,   464,  3797,   318,   257,   845,  1593,   636,
           286,   262,  3797,   338,  1204,    13,   632,   318,   262,   749]])

In [39]:
tokenizer.batch_decode(output_embed)

["<|endoftext|>\n\nThe cat is a very important part of the cat's life. It is the most"]

In [42]:
output_embed.size()

torch.Size([1, 20])

In [43]:
input_embeds.size()

torch.Size([1, 5, 768])

In [46]:
inputs.input_ids.size()

torch.Size([1, 5])

In [48]:
outputs

tensor([[2437,  284,  787,  257, 8263,  286,  257, 2095,  198,  198,  464,  717,
         1517,  345,  761,  284,  466,  318,  284, 3197]])

In [58]:
ok = torch.cat([inputs.input_ids, outputs], dim=-1)
ok

tensor([[2437,  284, 2513,  257, 3797, 2437,  284,  787,  257, 8263,  286,  257,
         2095,  198,  198,  464,  717, 1517,  345,  761,  284,  466,  318,  284,
         3197]])

In [68]:
# model(input_ids=ok[:, :-1], labels=ok[:, 1:])

In [85]:
inputs_embeds = model.get_input_embeddings()(ok[:, :-10])
inputs_embeds.size()

torch.Size([1, 15, 768])

In [87]:
# model(inputs_embeds=inputs_embeds, labels=ok[:, 10:])